# Generated by Django 4.2 on 2023-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('recruiter', 'Recruiter'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='admin', max_length=15),
        ),
    ]
