# Generated by Django 4.2.7 on 2023-11-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class'),
        ),
    ]
