# Generated by Django 4.2.7 on 2023-11-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='middle_name',
        ),
    ]
