# Generated by Django 4.2 on 2023-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
