# Generated by Django 4.2.7 on 2023-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Islam', 'Islam')], max_length=20),
        ),
    ]
