# Generated by Django 4.2.7 on 2023-12-01 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('VRF', 'Verified'), ('REJ', 'Rejected'), ('HOL', 'On Hold'), ('TSP', 'Test Passed'), ('TSF', 'Test Failed'), ('SHR', 'Shortlisted For Interview'), ('NSH', 'Not Shortlisted'), ('CLR', 'Cleared the process')], default='APL', max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=10)),
                ('slab', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('D', 'Dream')], max_length=10)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('can_placed_students_apply', models.BooleanField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('maximum_backlogs', models.IntegerField(blank=True, null=True)),
                ('maximum_active_backlogs', models.IntegerField(blank=True, null=True)),
                ('min_gpa', models.FloatField(blank=True, null=True)),
                ('eligible_courses', models.ManyToManyField(to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('applications', models.ManyToManyField(to='recruiter.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
