# Generated by Django 4.2.7 on 2023-11-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=10)),
                ('backlog_constraint', models.BooleanField(default=False)),
                ('active_backlog_constraint', models.BooleanField(default=False)),
                ('min_gpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('TEST', 'Test'), ('TECH INT', 'Technical Interview'), ('HR INT', 'HR Interview'), ('PLCD', 'Placed')], max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_shortlist', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterdata'),
        ),
    ]
