# Generated by Django 4.2.7 on 2023-11-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('VRF', 'Verified'), ('REJ', 'Rejected'), ('HOL', 'On Hold'), ('TSP', 'Test Passed'), ('TSF', 'Test Failed'), ('SHR', 'Shortlisted For Interview'), ('NSH', 'Not Shortlisted'), ('CLR', 'Cleared the process')], default='APL', max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
