# Generated by Django 4.2.7 on 2023-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='type',
            field=models.CharField(choices=[('VRF', 'Verified'), ('TSP', 'Test Passed'), ('SHR', 'Shortlisted For Interview'), ('CLR', 'Cleared the process')], default='VRF', max_length=3),
        ),
    ]
