# Generated by Django 4.2.7 on 2023-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_guardian_name_and_more'),
        ('recruiter', '0002_job_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eligible_departments',
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_courses',
            field=models.ManyToManyField(to='student.course'),
        ),
    ]
